name: '${archivesBaseName}'
main: 'com.otg.presetpacker.${modId}.PresetPackerSpigot'
version: '${version}'
author: '${author}'
loadbefore: [OpenTerrainGenerator]
load: STARTUP
api-version: 1.16
description: '${description}'
